# Generated by Django 2.1.8 on 2020-07-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='name',
            field=models.CharField(default=1, max_length=70, verbose_name=' Name'),
            preserve_default=False,
        ),
    ]
